worker_processes 1;

events { worker_connections 1024; }

http {
    include    /etc/nginx/mime.types;
    sendfile on;

    upstream unoa-backend {
        server unoa-backend:8000;
    }

    server {
        listen 80;
        server_name app.confeccionesunoa.com;

        # 🛡️ 1. Bloquear archivos sensibles
        location ~* /\.(env|git|htaccess|htpasswd|dockerenv|DS_Store)$ {
            return 444;
        }

        # 🛡️ 2. Bloquear escaneos WordPress (wp-admin, wp-includes, xmlrpc, wlwmanifest)
        location ~* /(wp-admin|wp-login\.php|wp-includes|wp-content|wordpress|xmlrpc\.php|wlwmanifest\.xml) {
            return 444;
        }

        # 🛡️ 3. Bloquear parámetros de debug PHP
        if ($query_string ~* "(XDEBUG_SESSION|phpstorm|eval\(|base64_encode)") {
            return 444;
        }

        # 🛡️ 4. Bloquear extensiones PHP/scripts del lado servidor
        location ~* \.(php|asp|aspx|jsp|cgi|sh|py|pl|rb)$ {
            return 444;
        }

        location /api {
            proxy_pass         http://unoa-backend;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }

        location /media/ {
            alias /media/;
        }

        location /public/ {
            alias /public/;
        }

        location / {
            root   /usr/share/nginx/html;
            index  index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}
